create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  task_id text,
  status text not null default 'opened' check (status in ('opened', 'started', 'completed', 'abandoned')),
  opened_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  last_seen_at timestamptz,
  total_items integer not null default 0,
  attempted_items integer not null default 0,
  correct_items integer not null default 0,
  task_accuracy double precision,
  completion_time_ms bigint,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sessions_task_id_idx on public.sessions (task_id);
create index if not exists sessions_status_idx on public.sessions (status);
